FROM node:18-alpine

WORKDIR /app

RUN apk add --no-cache curl

# Install dependencies for node-gyp
RUN apk add --no-cache python3 make g++

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
